docapp/urls.py
app_name = 'docapp'

from django.urls import path
from .views import index, register_request, login_request, logout_request, create_tutorial_page, create_tutorial, \
    subject_create_page, subject_create, content_create_page, content_create, tutorials, tutorials_active

urlpatterns = [
    path('', index, name='index'),
    path("register", register_request, name="register"),
    path("login", login_request, name="login"),
    path("logout", logout_request, name="logout"),
    path("create_tutorial_page", create_tutorial_page, name="create_tutorial_page"),
    path("create_tutorial", create_tutorial, name="create_tutorial"),
    path("subject_create_page/<str:generated_code>", subject_create_page, name="subject_create_page"),
    path("subject_create/<str:generated_code>", subject_create, name="subject_create"),
    path("content_create_page/<str:generated_code>", content_create_page, name="content_create_page"),
    path("content_create/<str:generated_code>", content_create, name="content_create"),
    path("tutorials_active/<str:generated_code_tut>/<str:generated_code_subject>", tutorials_active, name="tutorials_active"),

    path("tutorials/<str:generated_code>", tutorials, name="tutorials"),
    # path("tutorials/<str:generated_code>/<str:generated_code1>", tutorials_choose, name="tutorials_choose"),
]

doctut/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('docapp/', include('docapp.urls'))
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

docapp/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.conf import settings


# Create your models here.


class CustomUser(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    generated_code = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return self.generated_code


class Tutorials(models.Model):
    tutorial_name = models.CharField(max_length=200)
    generated_code = models.CharField(max_length=50, null=False, unique=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.tutorial_name


class Subjects(models.Model):
    subject_name = models.CharField(max_length=200)
    generated_code = models.CharField(max_length=50, unique=True, null=False)
    tutorial = models.ForeignKey(Tutorials, on_delete=models.CASCADE)

    def __str__(self):
        return self.subject_name


class Contents(models.Model):
    content = RichTextField()
    subject = models.ForeignKey(Subjects, on_delete=models.CASCADE)

docapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


docapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.shortcuts import render, HttpResponse, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages

from docapp.models import CustomUser, Tutorials, Subjects, Contents

from docapp.services import gen_code


def index(request):
    generated_code = gen_code()
    return render(request, 'index.html')


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            if request.user.is_authenticated and not CustomUser.objects.filter(author=request.user):
                custom_user = CustomUser(author=request.user, generated_code=gen_code())
                custom_user.save()
            messages.success(request, "Registration successful.")
            return redirect("docapp:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)

                messages.info(request, f"You are now logged in as {username}.")
                return redirect("docapp:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("docapp:index")


# ANOTHER VIEWS THAN AUTH
@login_required
def create_tutorial_page(request):
    try:
        tutorials = Tutorials.objects.all().filter(user=CustomUser.objects.get(author=request.user))
    except:
        tutorials = 'yoq'
    return render(request, 'tutorial_create.html', {"tutorials": tutorials, "envy": "envy"})


@login_required
def create_tutorial(request):
    if request.method == "POST":
        try:
            tutorial_name = request.POST.get('tutorial_name')
            custom_user = CustomUser.objects.get(author=request.user)
            generated_code = gen_code()
            tutorial = Tutorials(tutorial_name=tutorial_name, generated_code=generated_code, user=custom_user)
            tutorial.save()
        except Exception as error:
            print(error.__str__())
        return redirect("docapp:create_tutorial_page")


@login_required
def subject_create_page(request, generated_code):
    try:
        subjects = Subjects.objects.all().filter(tutorial=Tutorials.objects.get(generated_code=generated_code))
    except Exception as error:
        print(error.__str__())
        subjects = 'yoq'
    return render(request, "subject_create_page.html", {"generated_code": generated_code, "subjects": subjects})


@login_required
def subject_create(request, generated_code):
    try:
        subjects = Subjects.objects.all().filter(tutorial=Tutorials.objects.get(generated_code=generated_code))
    except Exception as error:
        print(error.__str__())
        subjects = 'yoq'
    try:
        if request.method == "POST":
            subject_name = request.POST.get('subject_name')
            generated_code1 = gen_code()
            subject = Subjects(tutorial=Tutorials.objects.get(generated_code=generated_code), subject_name=subject_name,
                               generated_code=generated_code1)
            subject.save()
    except Exception as error:
        print(error.__str__())

    return render(request, "subject_create_page.html", {"generated_code": generated_code, "subjects": subjects})


@login_required
def content_create_page(request, generated_code):
    try:
        contents = Contents.objects.all().filter(subject=Subjects.objects.get(generated_code=generated_code))
    except Exception as error:
        print(error.__str__())
        contents = 'yoq'
    return render(request, "content_create_page.html", {"generated_code": generated_code, "contents": contents})


@login_required
def content_create(request, generated_code):
    try:
        contents = Contents.objects.all().filter(subject=Subjects.objects.get(generated_code=generated_code))
    except Exception as error:
        print(error.__str__())
        contents = 'yoq'
    try:
        if request.method == "POST":
            content = request.POST.get('content')
            content = Contents(subject=Subjects.objects.get(generated_code=generated_code), content=content)
            content.save()
            print(content)
    except Exception as error:
        print(error.__str__())

    return render(request, "content_create_page.html", {"generated_code": generated_code, "contents": contents})


def tutorials(request, generated_code):
    tutorial = Tutorials.objects.get(generated_code=generated_code)
    subjects = Subjects.objects.all().filter(tutorial=tutorial)
    return render(request, 'tutorials.html', {"tutorial": tutorial, "subjects": subjects})


def tutorials_active(request, generated_code_tut, generated_code_subject):
    tutorial = Tutorials.objects.get(generated_code=generated_code_tut)
    if generated_code_subject == "envy":
        subjects = Subjects.objects.all().filter(tutorial=tutorial)
        contents = Contents.objects.all().filter(subject=Subjects.objects.all().filter(tutorial=tutorial)[0])
        return render(request, 'tutorials_active.html',
                      {"tutorial": tutorial, "subjects": subjects, "contents": contents})
    else:
        subjects = Subjects.objects.all().filter(tutorial=tutorial)
        contents = Contents.objects.all().filter(subject=Subjects.objects.get(generated_code=generated_code_subject))
        return render(request, 'tutorials_active.html',
                      {"tutorial": tutorial, "subjects": subjects, "contents": contents})

docapp/templates/content_create_page.html
{% extends "layout.html" %}

{% block title %}
content create page
{%endblock%}


{% block content %}
{% if user.is_authenticated %}


<div class="container">

    <div class="row justify-content-center">
        <div class="col-4 bg-light p-3">
            <form action="{% url 'docapp:content_create' generated_code %}" method="POST">
                {% csrf_token %}

                <input type="text" name="content" class="form-control" placeholder="subject name....">
                <button type="submit" class=" btn btn-sm btn-outline-primary mt-5">create subject</button>
            </form>
        </div>
    </div>
</div>



<div class="container">
    <div class="row justify-content-center">
        <div class="col-4 mt-5">
            {% for i in contents %}
            <p class="p-1 m-1 bg-light">{{i.content}}</p>

            {% empty %}
            <p class="text-center text-danger mt-5">you have no content yet. have a good time</p>
            {% endfor %}
        </div>
    </div>
</div>


{% else %}

<div class="container bg-light p-5 mt-5">
    <h2 class="text-center my-5"> Assalomu alaykum!</h2>
    <div class="row align-items-center justify-content-center">
        <div class="col-3 d-flex align-items-center justify-content-between ">

            <a href="{% url 'docapp:register'%}">Register</a>
            <a href="{% url 'docapp:login'%}">Log in</a>

        </div>
    </div>
</div>
{% endif %}

{% endblock %}

docapp/templates/index.html
{% extends 'layout.html' %}

{% block title %}Index Page{% endblock %}

{% block content %}


{% if user.is_authenticated %}
<p>Welcome, {{user.username}}</p>

<a href="{% url 'docapp:create_tutorial_page' %}">create new tutorial!</a>

<a class="nav-link" href="{% url 'docapp:logout' %}">Logout</a>
{% else %}


<div class="container bg-light p-5 mt-5">
    <h2 class="text-center my-5"> Assalomu alaykum!</h2>
    <div class="row align-items-center justify-content-center">
        <div class="col-3 d-flex align-items-center justify-content-between ">

            <a href="{% url 'docapp:register'%}">Register</a>
            <a href="{% url 'docapp:login'%}">Log in</a>

        </div>
    </div>
</div>
{% endif %}


{% endblock %}

docapp/templates/login.html
{% extends "layout.html" %}

{% block Title %} Log In {% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'docapp:register' %}">Create an account</a>.</p>
</div>

{% endblock %}

docapp/templates/register.html
{% extends "layout.html" %}
{% block title %} Register {% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'docapp:login' %}">login</a> instead.</p>
</div>


{% endblock %}

docapp/templates/subject_create_page.html
{% extends "layout.html" %}

{% block title %}
subject create page
{%endblock%}


{% block content %}
{% if user.is_authenticated %}


<div class="container">

    <div class="row justify-content-center">
        <div class="col-4 bg-light p-3">
            <form action="{% url 'docapp:subject_create' generated_code %}" method="POST">
                {% csrf_token %}
                <input type="text" name="subject_name" class="form-control" placeholder="subject name....">
                <button type="submit" class=" btn btn-sm btn-outline-primary mt-5">create subject</button>
            </form>
        </div>
    </div>
</div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-4">
            {% for i in subjects %}
            <a href="{% url 'docapp:content_create_page' i.generated_code %}" class="d-block text-primary p-1 mx-0 mt-2 bg-light">{{i.subject_name}}</a>

            {% empty %}
            <p class="text-center text-danger mt-5">you have no subjects yet. have a good time</p>
            {% endfor %}
        </div>
    </div>
</div>


{% else %}

<div class="container bg-light p-5 mt-5">
    <h2 class="text-center my-5"> Assalomu alaykum!</h2>
    <div class="row align-items-center justify-content-center">
        <div class="col-3 d-flex align-items-center justify-content-between ">

            <a href="{% url 'docapp:register'%}">Register</a>
            <a href="{% url 'docapp:login'%}">Log in</a>

        </div>
    </div>
</div>
{% endif %}

{% endblock %}

docapp/templates/tutorial_create.html
{% extends 'layout.html' %}

{% block title %}create tutorial page{% endblock %}

{% block content %}


{% if user.is_authenticated %}
<div class="container">
    <div class="row justify-content-end">
        <div class="col-4 d-flex align-items-center">
            <p class="m-0  me-5">Welcome, {{user.username}}</p>
            <a class="nav-link text-danger m-0" href="{% url 'docapp:logout' %}">Logout</a>
        </div>
    </div>
</div>

<div class="container">

    <div class="row justify-content-center">
        <div class="col-4 bg-light p-3">
            <form action="{% url 'docapp:create_tutorial' %}" method="POST">
                {% csrf_token %}
                <input type="text" name="tutorial_name" class="form-control" placeholder="tutorial name....">
                <button type="submit" class=" btn btn-sm btn-outline-primary mt-5">create tutorial</button>
            </form>
        </div>
    </div>
</div>


<div class="container" style="margin-top:70px">
    <h2 class="text-center mb-5">Tutorials:</h2>
    <div class="row justify-content-center">
        <div class="col-6">
            {% for i in tutorials %}
            <div class="d-flex justify-content-between">
                <a href="{% url 'docapp:subject_create_page' generated_code=i.generated_code %}"
                   class="d-block text-primary p-1 mx-0 mb-0 mt-2 bg-light">
                    {{i.tutorial_name}}
                </a>
                <a href="{% url 'docapp:tutorials_active' generated_code_tut=i.generated_code generated_code_subject=envy  %}"
                   class="d-block text-primary p-1 mx-0 mb-0 mt-2 bg-light" title="finished product link">{{i.generated_code}}</a>
            </div>
            {% empty %}
            <p class="text-center text-danger mt-5">you have no tutorials yet. have a good time</p>
            {% endfor %}


        </div>
    </div>
</div>
{% else %}

<div class="container bg-light p-5 mt-5">
    <h2 class="text-center my-5"> Assalomu alaykum!</h2>
    <div class="row align-items-center justify-content-center">
        <div class="col-3 d-flex align-items-center justify-content-between ">

            <a href="{% url 'docapp:register'%}">Register</a>
            <a href="{% url 'docapp:login'%}">Log in</a>

        </div>
    </div>
</div>
{% endif %}


{% endblock %}

docapp/templates/tutorials.html
{% extends "layout.html" %}

{% block title %}
{{tutorial.tutorial_name}}
{% endblock%}


{% block content %}
<div class="container-fluid py-5"  style="height:90vh">
    <div class="row">
        <div class="col-4 bg-light" style="height:90vh;">
            <h4 class="text-center">{{tutorial.tutorial_name}}</h4>
            {% for i in subjects %}
            <a href="{% url 'docapp:tutorials_active' generated_code_tut=tutorial.generated_code generated_code_subject=i.generated_code %}"
               class="d-block p-1 m-1 bg-white">{{i.subject_name}}
            </a>

            {% empty %}
            <p class="text-center text-danger mt-5">you have no subject yet. have a good time</p>
            {% endfor %}
        </div>

        <div class="col-8" style="height:90vh;overflow-y:scroll;">
            contents will be shown here...
        </div>
    </div>
</div>
{% endblock%}

docapp/templates/tutorials_active.html
{% extends "layout.html" %}

{% block title %}
{{tutorial.tutorial_name}}
{% endblock%}


{% block content %}
<div class="container-fluid py-5 "  style="height:90vh">
    <div class="row">
        <div class="col-4 bg-light"   style="height:90vh">
            <h4 class="text-center">{{tutorial.tutorial_name}}</h4>
            {% for i in subjects %}
            <a href="{% url 'docapp:tutorials_active' generated_code_tut=tutorial.generated_code generated_code_subject=i.generated_code %}"
               class="d-block p-1 m-1 bg-white">{{i.subject_name}}
            </a>

            {% empty %}
            <p class="text-center text-danger mt-5">you have no subject yet. have a good time</p>
            {% endfor %}
        </div>

        <div class="col-8"  style="height:90vh;overflow-y:scroll;">
            {% for i in contents %}
            <p  class="d-block p-2 mt-3 bg-light">{{i.content}}</p>

            {% empty %}
            <p class="text-center text-danger mt-5">you have no content yet. have a good time</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock%}